import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const alibabaFont = localFont({
  variable: "--font-alibaba",
  src: [
    {
      path: "../fonts/Alibaba-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Alibaba-Light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../fonts/Alibaba-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Alibaba-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "سفارت من | خدمات کنسولی صفارت افغانستان",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={alibabaFont.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
